-- MySQL Script generated by MySQL Workbench
-- 05/06/16 11:19:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pit_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pit_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pit_project`
  DEFAULT CHARACTER SET utf8;
USE `pit_project`;

-- -----------------------------------------------------
-- Table `pit_project`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Perfil` (
  `idPerfil`          INT         NOT NULL AUTO_INCREMENT,
  `nombrePerfil`      VARCHAR(45) NULL,
  `descripcionPerfil` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerfil`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pit_project`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Usuario` (
  `idUsuario`            INT         NOT NULL AUTO_INCREMENT,
  `nombreUsuario`        VARCHAR(45) NULL,
  `apellidoUsuario`      VARCHAR(45) NULL,
  `fechaRegistroUsuario` DATE        NULL,
  `emailUsuario`         VARCHAR(45) NULL,
  `passwordUsuario`      VARCHAR(45) NULL,
  `idPerfil`             INT         NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Perfil_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_Usuario_Perfil`
  FOREIGN KEY (`idPerfil`)
  REFERENCES `pit_project`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
