-- MySQL Script generated by MySQL Workbench
-- 05/26/16 01:54:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pit_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pit_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pit_project` DEFAULT CHARACTER SET utf8 ;
USE `pit_project` ;

-- -----------------------------------------------------
-- Table `pit_project`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nombrePerfil` VARCHAR(45) NULL,
  `descripcionPerfil` LONGTEXT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pit_project`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `apellidoUsuario` VARCHAR(45) NULL,
  `fechaRegistroUsuario` DATE NULL,
  `emailUsuario` VARCHAR(45) NULL,
  `passwordUsuario` VARCHAR(45) NULL,
  `imagenUsuario` LONGBLOB NULL,
  `imagenUsuarioBase64` MEDIUMTEXT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Perfil_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_Usuario_Perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `pit_project`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pit_project`.`Socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Socio` (
  `idSocio` INT NOT NULL AUTO_INCREMENT,
  `imagenSocioBase64` MEDIUMTEXT NULL,
  `nombreSocio` VARCHAR(45) NULL,
  `apellidoSocio` VARCHAR(45) NULL,
  `DNISocio` INT NULL,
  `fechaNacimientoSocio` DATE NULL,
  `sexoSocio` VARCHAR(45) NULL,
  `estadoCivilSocio` VARCHAR(45) NULL,
  `nombreConyugeSocio` VARCHAR(45) NULL,
  `apellidoConyugeSocio` VARCHAR(45) NULL,
  `departamentoNacimientoSocio` VARCHAR(45) NULL,
  `provinciaNacimientoSocio` VARCHAR(45) NULL,
  `distritoNacimientoSocio` VARCHAR(45) NULL,
  `departamentoResidenciaSocio` VARCHAR(45) NULL,
  `provinciaResidenciaSocio` VARCHAR(45) NULL,
  `distritoResidenciaSocio` VARCHAR(45) NULL,
  `direccionResidenciaSocio` VARCHAR(45) NULL,
  `telefonoFijoSocio` VARCHAR(45) NULL,
  `telefonoMovilSocio` VARCHAR(45) NULL,
  `emailSocio` VARCHAR(45) NULL,
  `passwordSocio` VARCHAR(45) NULL,
  `fechaRegistroSocio` DATE NULL,
  `imagenFirmaSocio` LONGBLOB NULL,
  `imagenHuellaSocio` LONGBLOB NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSocio`),
  INDEX `fk_Socio_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Socio_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `pit_project`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pit_project`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NULL,
  `precioProducto` DOUBLE NULL,
  `descripcionProducto` VARCHAR(45) NULL,
  `tasaProducto` DOUBLE NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pit_project`.`Obligacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Obligacion` (
  `idObligacion` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistroObligacion` DATE NULL,
  `numeroCuotasObligacion` INT NULL,
  `idSocio` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idObligacion`),
  INDEX `fk_Obligacion_Socio1_idx` (`idSocio` ASC),
  INDEX `fk_Obligacion_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Obligacion_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_Obligacion_Socio1`
    FOREIGN KEY (`idSocio`)
    REFERENCES `pit_project`.`Socio` (`idSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obligacion_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `pit_project`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obligacion_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `pit_project`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pit_project`.`Cuota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Cuota` (
  `idCuota` INT NOT NULL AUTO_INCREMENT,
  `fechaPagoCuota` DATE NULL,
  `montoCuota` DOUBLE NULL,
  `capitalCuota` DOUBLE NULL,
  `interesCuota` DOUBLE NULL,
  `estadoCuota` VARCHAR(45) NULL,
  `idObligacion` INT NOT NULL,
  PRIMARY KEY (`idCuota`),
  INDEX `fk_Cuota_Obligacion1_idx` (`idObligacion` ASC),
  CONSTRAINT `fk_Cuota_Obligacion1`
    FOREIGN KEY (`idObligacion`)
    REFERENCES `pit_project`.`Obligacion` (`idObligacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pit_project`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pit_project`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistroPago` DATE NULL,
  `montoPago` DOUBLE NULL,
  `metodoPago` VARCHAR(45) NULL,
  `idCuota` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_Pago_Cuota1_idx` (`idCuota` ASC),
  INDEX `fk_Pago_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Pago_Cuota1`
    FOREIGN KEY (`idCuota`)
    REFERENCES `pit_project`.`Cuota` (`idCuota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `pit_project`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
